@echo off
echo Initializing Git repository...
git init

echo Adding all files...
git add .

echo Creating commit...
git commit -m "Initial commit: Village website with MongoDB integration and bug fixes"

echo Adding remote repository...
git remote add origin https://github.com/sujeetdon07/village-website.git

echo Setting branch to main...
git branch -M main

echo Pushing to GitHub...
git push -u origin main

echo.
echo Done! Press any key to exit...
pause
